# Generated by Django 4.2.2 on 2026-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_remove_article_date_article_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
